### PR TITLE
converts code to Swift3 (syntax, style & deprecations)

### PR DESCRIPTION
**Pull request by buffstop**
Converts code to Swift3. Syntax, style & deprecations.

### CODE REVIEW

**Comment by wangjwchn** [comment]
Hi,@buffstop
Thanks for your help! It's looks better.
I think this MR has some problems with CI as is mentioned above, and dropping the version of swift-2.3  is not a good idea because that version's API is frozen.I suggest creating a new branch for the version of swift-3.0 .

**Comment by wangjwchn** [comment]
@buffstop
I've created a new branch called 'Swift3' ,please merge your code into this branch.

**Comment by wangjwchn** [comment]
@buffstop
Can we close this MR now?

**Comment by buffstop** [comment]
Shure. Whats wrong with CI though?

**Pull request closed without merging**
